# Generated by Django 4.2.6 on 2023-10-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elektromer_app', '0002_balance_solar_historicalbalance_solar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_main',
            name='svj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.svj'),
        ),
        migrations.AddField(
            model_name='balance_solar',
            name='svj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.svj'),
        ),
        migrations.AddField(
            model_name='balance_sub',
            name='svj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.svj'),
        ),
        migrations.AddField(
            model_name='flat',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.customer'),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='historicalbalance_main',
            name='svj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.svj'),
        ),
        migrations.AddField(
            model_name='historicalbalance_solar',
            name='svj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.svj'),
        ),
        migrations.AddField(
            model_name='historicalbalance_sub',
            name='svj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.svj'),
        ),
        migrations.AddField(
            model_name='historicalflat',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.customer'),
        ),
        migrations.AddField(
            model_name='historicalflat',
            name='flat_number',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Sub_chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.customer')),
                ('svj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.svj')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSub_chairman',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('svj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.svj')),
            ],
            options={
                'verbose_name': 'historical sub_chairman',
                'verbose_name_plural': 'historical sub_chairmans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
