# Generated by Django 4.2.6 on 2023-10-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0003_alter_historicalsvj_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_orientation_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gsm_modul',
            name='svj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.svj'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_orientation_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
