# Generated by Django 4.2.6 on 2023-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0003_balance_main_svj_balance_solar_svj_balance_sub_svj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsvj',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='svj',
            name='to_date',
            field=models.DateField(),
        ),
    ]
