# Generated by Django 4.2.6 on 2023-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0004_alter_historicalsvj_to_date_alter_svj_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gsm_modul',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalchairman',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalflat',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalgsm_modul',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalmain_electrometer',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalsolar_electrometer',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalsub_chairman',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='main_electrometer',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solar_electrometer',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sub_chairman',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sub_electrometer',
            name='to_date',
            field=models.DateField(),
        ),
    ]
