# Generated by Django 4.2.6 on 2023-10-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0005_alter_chairman_to_date_alter_flat_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gsm_modul',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalchairman',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalflat',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalgsm_modul',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalmain_electrometer',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalsolar_electrometer',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalsub_chairman',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalsvj',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_electrometer',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='solar_electrometer',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sub_chairman',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sub_electrometer',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='svj',
            name='to_date',
            field=models.DateField(blank=True),
        ),
    ]
