# Generated by Django 4.2.6 on 2023-12-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0006_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
