# Generated by Django 4.2.6 on 2023-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0008_remove_chairman_to_date_remove_flat_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsvj',
            name='number_of_flats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='svj',
            name='number_of_flats',
            field=models.IntegerField(default=0),
        ),
    ]
