# Generated by Django 4.2.6 on 2023-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0009_historicalsvj_number_of_flats_svj_number_of_flats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_number_subscription',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_orientation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_postal_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_number_subscription',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_orientation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_postal_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalsvj',
            name='address_number_subscription',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalsvj',
            name='address_orientation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalsvj',
            name='address_postal_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='svj',
            name='address_number_subscription',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='svj',
            name='address_orientation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='svj',
            name='address_postal_code',
            field=models.IntegerField(default=0),
        ),
    ]
