# Generated by Django 4.2.6 on 2023-12-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0010_remove_balance_solar_solar_electrometer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='gsm_modul',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_from_date',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_to_date',
        ),
        migrations.RemoveField(
            model_name='historicalflat',
            name='gsm_modul',
        ),
        migrations.RemoveField(
            model_name='historicalflat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalflat',
            name='owner_from_date',
        ),
        migrations.RemoveField(
            model_name='historicalflat',
            name='owner_to_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_number_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_orientation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_number_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_orientation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
