# Generated by Django 4.2.6 on 2023-10-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0010_alter_customer_address_number_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_main',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='balance_solar',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='balance_sub',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='historicalbalance_main',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='historicalbalance_solar',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='historicalbalance_sub',
            name='identification_number',
        ),
    ]
