# Generated by Django 4.2.6 on 2023-10-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0011_remove_balance_main_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_solar',
            name='solar_electrometer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.solar_electrometer'),
        ),
        migrations.AlterField(
            model_name='historicalbalance_solar',
            name='solar_electrometer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.solar_electrometer'),
        ),
    ]
