# Generated by Django 4.2.6 on 2023-10-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0012_alter_balance_solar_solar_electrometer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_main',
            name='main_electromer',
        ),
        migrations.RemoveField(
            model_name='historicalbalance_main',
            name='main_electromer',
        ),
        migrations.AddField(
            model_name='balance_main',
            name='main_electrometer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elektromer_app.main_electrometer'),
        ),
        migrations.AddField(
            model_name='historicalbalance_main',
            name='main_electrometer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elektromer_app.main_electrometer'),
        ),
    ]
