# Generated by Django 4.2.6 on 2023-12-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0012_flat_address_city_flat_address_kraj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsvj',
            old_name='low_form',
            new_name='law_form',
        ),
        migrations.RenameField(
            model_name='svj',
            old_name='low_form',
            new_name='law_form',
        ),
    ]
