# Generated by Django 4.2.6 on 2023-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0013_rename_low_form_historicalsvj_law_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsvj',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='svj',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
