# Generated by Django 4.2.6 on 2023-10-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0013_remove_balance_main_main_electromer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolar_electrometer',
            name='status',
            field=models.CharField(choices=[('Aktivní', 'Aktivní'), ('Pozastavené', 'Pozastavené'), ('Neaktivní', 'Neaktivní')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solar_electrometer',
            name='status',
            field=models.CharField(choices=[('Aktivní', 'Aktivní'), ('Pozastavené', 'Pozastavené'), ('Neaktivní', 'Neaktivní')], max_length=150, null=True),
        ),
    ]
