# Generated by Django 4.2.6 on 2023-10-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0014_historicalsolar_electrometer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsvj',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='svj',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
