# Generated by Django 4.2.6 on 2023-10-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsvj',
            name='address_orientation_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='svj',
            name='address_orientation_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
