# Generated by Django 4.2.6 on 2023-10-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektromer_app', '0002_alter_historicalsvj_address_orientation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsvj',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='svj',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
